
project_id = "tfyybwoxraxvpkjbwyyq"

[api]
port = 54321
hostname = "127.0.0.1"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324

[functions]
[functions.add-avatar-url-column]
verify_jwt = false
