
project_id = "tfyybwoxraxvpkjbwyyq"

[api]
enabled = true

[api.serve]
port = 54321
hostname = "127.0.0.1"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
port = 54325

[auth]
port = 54326

[realtime]
port = 54327

[functions]
[functions.add-avatar-url-column]
verify_jwt = false
