
project_id = "tfyybwoxraxvpkjbwyyq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions]
[functions.send-notification]
verify_jwt = true
