// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfyybwoxraxvpkjbwyyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmeXlid294cmF4dnBramJ3eXlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NDUxMTEsImV4cCI6MjA1ODQyMTExMX0.a2yZkXlTJVO_GSn79vWbNWAmtp7WfMnKR8FpLDj06PY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);